# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfKK2QduHKO7DwWpEQoQX1fBzDkGogPt
"""

#Assignment Day 1

a=int(input('Enter First Variable:'))
b=int(input('Enter Second Variable:'))
c=pow(a,b)
print(c)